import React from 'react'


export default function Head() {
    return (
        <div>

            <title>Cookie Stand Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />


        </div>
    )
}
