import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "tailwindcss/tailwind.css"
import Header from '../components/Header'
import Mian from '../components/Mian'
import Footer from '../components/Footer'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Mian />

      <Footer />



    </div>
  )
}
